import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import Menu from '../components/Menu'; // Assuming you created a HamburgerMenu component
import Footer from '../components/Footer';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased min-h-screen flex flex-col`}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}

